# Install caesar
Pkg.update()
Pkg.add("RoME")
Pkg.add("Caesar")
Pkg.checkout("Caesar")
Pkg.add("Neo4j")
Pkg.add("Mongo")
Pkg.add("CloudGraphs")
Pkg.checkout("CloudGraphs")
Pkg.add("Unmarshal")
Pkg.add("ArgParse")
Pkg.add("Mux")
Pkg.add("HTTP")
Pkg.add("Suppressor")
Pkg.build("Caesar")